title: "10分でなんとなくわかる！ - Docker -"
summary: | 
  Dcokerを素早く理解するための本です。
  前半は、Dockerとはなにかという話。
  後半は、ハンズオン形式でDockerを理解する構成になっています。
  一通り読んだ後には、Dockerでの環境構築が自分でできるようになっているはずです。
  書きたいことを盛り込んでいたら10分じゃ終わらなくなってきました。
  前半だけで10分ということでご了承ください。
  後半のハンズオン部分は、じっくり取り組んでください。
  現在書き途中です。
  ハンズオン部分の公開は、随時公開していく予定です。
topics: [docker, dockerdesktop, コンテナ, 仮想化, 入門]
published: true
allow_override: true
price: 300 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 1-epilogue
  - 2-what-is-docker
  - 3-hands-on-setup
  - 4-hands-on-basic-commands
  - 5-hands-on-dockerfile
  - 6-hands-on-docker-compose
  - 7-hands-on-best-practices
  - 8-appendix
